src/WebApp/BugsTracker/Areas/Tracker/Controllers/LogController.cs
using BugTracker.Application.Features.Audits.Queries.GetAllLogs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BugTracker.Areas.Tracker.Controllers
{
    [Authorize(Roles = "Admin, Demo Admin")]
    public class LogController : BaseController
    {
        public async Task<IActionResult> GetAll(int page = 1, string searchstring = null)
        {
            var response = await Mediator.Send(new GetAllLogsQuery(page, searchstring));
            response.Data.Pager.SearchText = searchstring;
            return View(response.Data);
        }
    }
}

src/WebApp/BugsTracker/Areas/Tracker/Controllers/TicketController.cs
using BugTracker.Application.Dto.Comments;
using BugTracker.Application.Dto.Projects;
using BugTracker.Application.Dto.Tickets;
using BugTracker.Application.Enums;
using BugTracker.Application.Features.Audits.Queries;
using BugTracker.Application.Features.Comments.Commands.Create;
using BugTracker.Application.Features.Comments.Queries.GetAll;
using BugTracker.Application.Features.ProjectTeam.Queries.GetAllAccessibleMembers;
using BugTracker.Application.Features.TicketConfigurations.Queries.GetAll;
using BugTracker.Application.Features.Tickets.Commands.Create;
using BugTracker.Application.Features.Tickets.Commands.Delete;
using BugTracker.Application.Features.Tickets.Commands.Update;
using BugTracker.Application.Features.Tickets.Queries.GetProjectTickets;
using BugTracker.Application.Features.Tickets.Queries.GetTicket;
using BugTracker.Application.Features.Tickets.Queries.GetTicketsByUser;
using BugTracker.Application.Features.TicketTeam.Query;
using BugTracker.Application.Features.TicketTeam.Query.GetCurrentTeam;
using BugTracker.Application.Responses;
using BugTracker.Filters.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.Areas.Tracker.Controllers
{
    public class TicketController : BaseController
    {
        private const string ModalBasePath = "~/Areas/Tracker/Views/Shared/Partial/Ticket/";
        private const string ModalType = "TicketModalPartial.cshtml";

        private const string CreateModalPath = ModalBasePath + "_create" + ModalType;
        private const string UpdateModalPath = ModalBasePath + "_update" + ModalType;
        private const string DeleteModalPath = ModalBasePath + "_delete" + ModalType;
        private const string DetailsModalPath = ModalBasePath + "_details" + ModalType;
        private const string CommentModalPath = ModalBasePath + "_comment" + ModalType;
        private const string ProjectTeamModalPath = "~/Areas/Tracker/Views/Shared/Partial/Project/_projectTeamModalPartial.cshtml";


        public async Task<IActionResult> ByUser(
            int page = 1,
            string searchString = "",
            bool showOnlyCreated = false, bool showAll = true)
        {
            ViewData["showOnlyCreated"] = showOnlyCreated;
            var response = await Mediator.Send(new GetTicketByUserQuery(page, searchString, showOnlyCreated, showAll));
            response.Data.Pager.SearchText = searchString != null ? searchString : "";
            response.Data.ShowOnlyCreated = showOnlyCreated;
            return View(response.Data);
        }


        [ValidationFilter]
        public async Task<IActionResult> ByProject(
            Guid projectId,
            List<string> errors,
            int page = 1,
            string searchString ="",
            bool isSuccess = false, bool isFailed = false,
            string type = "ticket", string actionReturned = null)
        {
            ViewBag.isSuccess = isSuccess;
            ViewBag.isFailed = isFailed;
            ViewBag.Type = type;
            ViewBag.actionReturned = actionReturned;
            ViewBag.errors = errors;

            var response = await Mediator.Send(new GetProjectTicketsQuery(projectId, page, searchString));
            response.Data.Pager.SearchText = searchString != null ? searchString : "";
            return View("ProjectTickets", response);
        }
        
        [HttpPost]
        [Authorize(Roles ="Admin, Submitter")]
        public async Task<IActionResult> Create(CreateTicketCommand command, int page)
        {
            var response = await Mediator.Send(command);
            if (response.Succeeded)
            {
                return RedirectToAction("ByProject", new { projectId = command.ProjectId, isSuccess = true, type = "ticket", actionReturned = "created", page = page });
            }
            return RedirectToAction("ByProject", new { projectId = command.ProjectId, isFailed = true, type = "ticket", actionReturned = "created", page = page });
        }

        [HttpPost]
        [Authorize(Policy ="NoDemo")]
        public async Task<IActionResult> Update(UpdateTicketCommand command, Guid projectId, int page)
        {
            var response = await Mediator.Send(command);
            if (response.Succeeded)
            {
                return RedirectToAction("ByProject", new { projectId = projectId, isSuccess = true, type = "ticket", actionReturned = "updated", page = page });
            }
            return RedirectToAction("ByProject", new { projectId = projectId, isFailed = true, actionReturned = "updated", errors = response.ErrorMessages, page = page});
        }

        [HttpPost]
        [Authorize(Policy = "PriviledgedUser")]
        public async Task<IActionResult> Delete(DeleteTicketCommand command, Guid projectId, int page)
        {
            var response = await Mediator.Send(command);
            if (response.Succeeded)
            {
                return RedirectToAction("ByProject", new { projectId = projectId, isSuccess = true, type = "ticket", actionReturned = "deleted", page = page });
            }
            return RedirectToAction("ByProject", new { isFailed = true, page = page });
        }

        [HttpGet]
        [Authorize(Policy = "NotDev")]
        public async Task<IActionResult> LoadCreateModal(Guid projectId, [FromQuery] int page)
        {
            var dto = new CreateTicketDto(projectId);

            var teamResponse = await Mediator.Send(new GetAllAccessibleTicketMembersQuery(projectId));
            var ticketConfigurationResponse = await Mediator.Send(new GetAllTicketConfigurationsQuery());
            dto.Team = teamResponse.DataList;
            dto.TicketConfigurations = ticketConfigurationResponse.Data;

            return PartialView(CreateModalPath, dto);
        }
        
        [HttpGet]
        public async Task<IActionResult> LoadUpdateModal(Guid id, Guid projectId)
        {
            var dto = new UpdateTicketDto(id);

            var ticket = (await Mediator.Send(new GetTicketQuery(id))).Data;

            var teamResponse = await Mediator.Send(new GetAllAccessibleTicketMembersQuery(projectId));
            var ticketConfigurationResponse = await Mediator.Send(new GetAllTicketConfigurationsQuery());

            dto.ProjectId = projectId;
            dto.Team = teamResponse.DataList;
            dto.TicketConfigurations = ticketConfigurationResponse.Data;

            dto.Command = new UpdateTicketCommand(id);
            dto.Command.Name = ticket.Name;
            dto.Command.Description = ticket.Description;
            dto.Command.PriorityId = ticket.Priority.Id;
            dto.Command.TypeId = ticket.Type.Id;
            dto.Command.StatusId = ticket.Status.Id;
            dto.Command.Team = ticket.TicketsTeamMembers.Select(ttm => ttm.Id).ToList();
            dto.Command.EstimatedAmountOfHours = ticket.EstimatedAmountOfHours;

            return PartialView(UpdateModalPath, dto);
        }
        
        [HttpGet]
        [Authorize(Policy = "NotDev")]
        public IActionResult LoadDeleteModal(Guid id, Guid projectId, string name)
        {
            var dto = new DeleteTicketDto(id, projectId, name);
            return PartialView(DeleteModalPath, dto);
        }

        [HttpGet]
        public async Task<IActionResult> LoadDetailsModal(Guid ticketId)
        {
            var dto = new TicketDetailsDto();

            var historyResponse = await Mediator.Send(new GetAuditLogsQuery(ticketId, AuditableType.Ticket));
            var commentsResponse = await Mediator.Send(new GetAllCommentsQuery(ticketId));
            var teamResponse = await Mediator.Send(new GetCurrentTeamQuery(ticketId));

            dto.TicketId = ticketId;
            dto.History = historyResponse.DataList;
            dto.Comments = commentsResponse;
            dto.Team = teamResponse.DataList;

            return PartialView(DetailsModalPath, dto);
        }

        [HttpGet]
        [Authorize(Policy = "PriviledgedUser")]
        public async Task<IActionResult> LoadProjectTeamModal(Guid projectId)
        {
            var dto = new ProjectTeamManagementDto();
            var teamResponse = await Mediator.Send(new GetAllAccessibleProjectMembersQuery());

            dto.ProjectId = projectId;
            dto.Team = teamResponse.DataList;

            return PartialView(ProjectTeamModalPath);
        }
    
        [HttpPost]
        [Authorize(Policy = "NoDemo")]
        public async Task<PartialViewResult> SendComment(CreateCommentDto request)
        {
            var response = new ApiResponse<CommentDto>();

            var createdCommentResponse = await Mediator.Send(new CreateCommentCommand(request.Message, request.TicketId));
            var commentResponse = await Mediator.Send(new GetAllCommentsQuery(request.TicketId));

            response.DataList = commentResponse.DataList;
            response.Data = commentResponse.Data;

            if (!createdCommentResponse.Succeeded)
            {
                response.Succeeded = false;
                response.ErrorMessages = createdCommentResponse.ErrorMessages;
            }

            return PartialView(CommentModalPath, response);

        }
    }
}

src/WebApp/BugsTracker/Areas/Tracker/Controllers/UserController.cs
using BugTracker.Application.Dto.UserManagement;
using BugTracker.Application.Features.UserManagement.Commands.DeleteUser;
using BugTracker.Application.Features.UserManagement.Commands.LockUser;
using BugTracker.Application.Features.UserManagement.Commands.UnlockUser;
using BugTracker.Application.Features.UserManagement.Commands.UpdateUserRole;
using BugTracker.Application.Features.UserManagement.GetAllRoles;
using BugTracker.Application.Features.UserManagement.GetAllUsers;
using BugTracker.Application.Features.UserManagement.GetUserWithRoles;
using BugTracker.Application.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BugTracker.Areas.Tracker.Controllers
{
    [Authorize(Roles ="Admin, Demo Admin")]
    public class UserController : BaseController
    {
        private const string ModalBasePath = "~/Areas/Tracker/Views/Shared/Partial/UserManagement/";
        private const string ModalType = "UserManagementModalPartial.cshtml";

        private const string ManageRolesModalPath = ModalBasePath + "_manageRole" + ModalType;
        private const string LockUserModalPath = ModalBasePath + "_lock" + ModalType;
        private const string UnlockUserModalPath = ModalBasePath + "_unlock" + ModalType;
        private const string DeleteUserModalPath = ModalBasePath + "_delete" + ModalType;

        public async Task<IActionResult> GetAll(int page = 1, string searchString = null, bool showLocked = false, bool showNoRole = false,
            bool isSuccess = false, bool isFailed = false, List<string> errors = null, string type = null, string actionReturned = null)
        {
            ViewBag.isSuccess = isSuccess;
            ViewBag.isFailed = isFailed;
            ViewBag.errors = errors;
            ViewBag.type = type;
            ViewBag.actionReturned = actionReturned;

            var response = await Mediator.Send(new GetAllUsersQuery(page, searchString, showLocked, showNoRole));
            return View(response.Data);
        }

        public async Task<IActionResult> LoadManageRoleModal(string uid, [FromQuery] int page)
        {
            var vm = new ManageUserRoleViewModel();

            var userRolesResponse = await Mediator.Send(new GetUserWithRoleQuery(uid));
            var rolesResponse = await Mediator.Send(new GetAllRolesQuery());

            vm.UserWithRoles = userRolesResponse.Data; 
            vm.AvailableRoles = rolesResponse.DataList;
            vm.Page = page;

            return PartialView(ManageRolesModalPath, vm);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ManageUserRoles(UserWithRoleDto userWithRoles,int page)
        {
            var response = await Mediator.Send(new UpdateUserRolesCommand(userWithRoles.UserId, userWithRoles.SelectedRoles));
            if (!response.Succeeded)
            {
                //TODO manage errors
            }

            return RedirectToAction("GetAll", new { isSuccess = true, type = "user role", actionReturned = "uptaded", page = page });
        }
        
        public IActionResult LoadLockUserModal(string uid, [FromQuery] int page)
        {
            var vm = new ManageUserStateViewModel(uid,page);
            return PartialView(LockUserModalPath, vm);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult>Lock(string uid, int page)
        {
            var lockResponse = await Mediator.Send(new LockUserCommand(uid));
            if (!lockResponse.Succeeded)
            {
                return RedirectToAction("GetAll", new {isFailed = true, errors = lockResponse.ErrorMessages, page = page });
            }

            return RedirectToAction("GetAll", new { isSuccess = true, type = "user", actionReturned = "locked", page = page});
        }
        
        public IActionResult LoadUnlockUserModal(string uid, [FromQuery] int page)
        {
            var vm = new ManageUserStateViewModel(uid, page);

            return PartialView(UnlockUserModalPath, vm);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UnLock(string uid, int page)
        {
            var lockResponse = await Mediator.Send(new UnlockUserCommand(uid));
            if (!lockResponse.Succeeded)
            {
                return RedirectToAction("GetAll", new {isFailed = true, errors = lockResponse.ErrorMessages, type = "user", actionReturned = "unlocked", page = page });
            }

            return RedirectToAction("GetAll", new { isSuccess = true, type = "user", actionReturned = "unlocked",page = page });
        }
        
        public IActionResult LoadDeleteUserModal(string uid, [FromQuery]int page)
        {
            var vm = new ManageUserStateViewModel(uid, page);
            return PartialView(DeleteUserModalPath, vm);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string uid, int page)
        {
            var deleteResponse = await Mediator.Send(new DeleteUserCommand(uid));
            if (!deleteResponse.Succeeded)
            {
                return RedirectToAction("GetAll", new { isFailed = true, errors = deleteResponse.ErrorMessages, type = "user", actionReturned = "deleted" });
            }

            return RedirectToAction("GetAll", new { isSuccess = true, type = "user", actionReturned = "deleted", page = page });
        }
    }
}

src/WebApp/BugsTracker/Areas/Tracker/Views/Shared/_TrackerLayout.cshtml
@using System.Security.Claims
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor
@{ 
    var userRoles = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Role).Value;
    var roles = _httpContextAccessor.HttpContext.User.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToList();
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/tracker.css" />

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
</head>
<body>
    <div class="wrapper">
        <div class="body-overlay"></div>
        <!--------Sidebar-------->
        <nav class="sidebar" id="sidebar">
            
            <div class="sidebar-header">
                <i class="fab fa-hornbill"></i>
                <h3>Bug Tracker</h3>
                <div class="mt-2">
                    <p class="text-center">- Welcome @Context.User.Identity.Name -</p>
                    <p class="text-center">Current role: <span>@userRoles</span></p>


                </div>
            </div>

            <ul class="list-unstyled  d-flex flex-column">
                <li class="active">
                    <a asp-controller="Home" asp-action="Dashboard" class="dashboard">
                        <i class="fas fa-chart-bar"></i><span>Dashboard</span>
                    </a>
                </li>

                <li id="tickets-management-link">
                    <a asp-controller="Ticket" asp-action="ByUser">
                        <i class="fas fa-ticket-alt"></i><span>Tickets</span>
                    </a>
                </li>

                @{
                    if (User.IsInRole("Admin") || User.IsInRole("Demo Admin"))
                    {
                        <li id="user-management-link">
                            <a asp-controller="User" asp-action="GetAll">
                                <i class="fas fa-user-tag"></i><span>User management</span>
                            </a>
                        </li>

                        <li id="logs-management-link">
                            <a asp-controller="Log" asp-action="GetAll">
                                <i class="fa fa-history" aria-hidden="true"></i>
                                <span>Change Tracker</span>
                            </a>
                        </li>
                    }
                }

                <li id="logout-holder" class="align-bottom">
                    <a asp-controller="Account" asp-action="logout" asp-area="Identity" class="x-btn red" id="logout-link">
                        <span>Logout</span> <i class="fas fa-sign-out-alt" id="logout-icon"></i>
                    </a>
                </li>
            </ul>


        </nav>

        <!-- Page content -->

        <div id="content">
            <partial name="../Shared/Partial/Common/_resultAlertPartial.cshtml" />

            <div class="d-flex navigation-items-holder">
                <button type="button" id="sidebar-collapse" class="d-xl-block d-lg-block d-md-none d-none">
                    <span><i class="fas fa-caret-square-left"></i></span>
                </button>

                <p class="navbar-brand" id="sectionName" href="#">Dashboard</p>
            </div>
            <!-- Top navbar -->
            <div class="top-navbar">
                <nav class="navbar navbar-expand-lg">

                    <button class="d-inline-block d-lg-none ml-auto more-button" type="button" data-toggle="collapse"
                            data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle">
                        <span><i class="fas fa-ellipsis-v"></i></span>
                    </button>
                </nav>
            </div>

            <!-------------- Main content --------------->

            <div class="main-content">

                @RenderBody()

            </div>

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {

            var navBarState = localStorage.getItem('navbar-state');
            if (localStorage.getItem('navbar-state') && localStorage.getItem('navbar-state') === "false") {
                $('.sidebar').addClass('active');
                $('#content').addClass('active');
            }
            console.log(navBarState)
            $('#sidebar-collapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $('#content').toggleClass('active');
                $(this).toggleClass('active');
                $(".navigation-items-holder").toggleClass('folded');

                if (!$('#sidebar').hasClass("active")) {
                    localStorage.setItem('navbar-state', true)
                }
                else {
                    localStorage.setItem('navbar-state', false)

                }
            });

            $('.more-button,.body-overlay').on('click', function () {
                console.log("clicked")
                $('#sidebar,.body-overlay').toggleClass('show-nav');
            });


        });

    </script>
</body>
</html>